### PR TITLE
Introduced GitHub Actions for linting

### PR DESCRIPTION
**Pull request by dimsanius**
Hey there,

I have introduced GitHub Actions to run linting on pull requests and/or push'es to `master` or branch.
It basically runs prospector using windows platform. It addresses this issue: https://github.com/Meru3m/virtualbox-snapshotter/issues/17

Moreover, I propose to introduce linting checks to be mandatory before merging pull requests. This can be achieved the following way:
- `Settings` -> `Branches` -> `Add branch protection rule`:
   - `Branch name pattern`: `master`
   - Tick `Require status checks to pass before merging`
      - Select `Linter` from the text box

### CODE REVIEW

**Comment by mattiabaldari** [comment]
Hi @dimsanius I'll merge it and set what you asked

**Comment by mattiabaldari** [comment]
@dimsanius I do not see any `Linter` text box here:
image

**Comment by dimsanius** [comment]
Hmm, it seem to struggle finding status checks. I think it may be named `Prospector` or `Code checks`.
I do see that workflow was run successfully already (https://github.com/Meru3m/virtualbox-snapshotter/actions/runs/6693664249). Maybe it was still running the workflow - it took around 3min to finish. Could you check it again, please?

**Comment by mattiabaldari** [comment]
@dimsanius it worked with Prospector ;) thank you!

**Pull request merged**
